version: 0.1

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn package shade:shade
      - mv target/hello-1.0.jar .
artifacts:
  files:
    - hello-1.0.jar