version: 0.1

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn package shade:shade
      - mv target/ollytest_artid-1.0-SNAPSHOT.jar .
artifacts:
  files:
    - ollytest_artid-1.0-SNAPSHOT.jar